baseURL = "https://kontlk.github.io/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "KoNLTK and KoNLP"
theme = "docdock"
themesDir = "themes"
publishDir = "docs"


[params]
editURL = "https://github.com/konltk/konltk.github.io/edit/master/web/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false

[outputs]
home = [ "HTML", "RSS", "JSON"]