baseURL = "https://kontlk.github.io/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "KoNLTK"
theme = "docdock"
themesDir = "themes"
publishDir = "docs"

# this is added by hyunyoung2 for initial setting 
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


# [Languages]
# [Languages.en]
# title = "Documentation for Hugo docDock"
# weight = 1
# languageName = "English"
# 
# [Languages.fr]
# title = "Documentation du thème docDock"
# weight = 2
# languageName = "Français"

[params]
editURL = "https://github.com/konltk/konltk.github.io/edit/master/web/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false

# This was added by hyunyoung2 for initial setting
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true


[outputs]
home = [ "HTML", "RSS", "JSON"]

# For initial setting 
[[menu.shortcuts]]
name = "<i class=''></i> <label>News</label>"
url = "/"
weight = 10

[[menu.shortcuts]]
name = "<i class=''></i> <label>Installing</label>"
url = "/contents/installing-konltk/"
weight = 11

[[menu.shortcuts]]
name = "<i class=''></i> <label>Installing Data</label>"
url = "/"
weight = 12

[[menu.shortcuts]]
name = "<i class=''></i> <label>Contribute</label>"
url = "/"
weight = 13

[[menu.shortcuts]]
name = "<i class=''></i> <label>FAQ</label>"
url = "/"
weight = 14

[[menu.shortcuts]]
name = "<i class=''></i> <label>Wiki</label>"
url = "/"
weight = 15

[[menu.shortcuts]]
name = "<i class=''></i> <label>API</label>"
url = "/"
weight = 16

[[menu.shortcuts]]
name = "<i class=''></i> <label>HOW TO</label>"
url = "/"
weight = 17